### ISSUE TITLE
Class 'Yar_Server' not found

### ISSUE THREAD

**Issue by ghost** [starlight36/yar-client-java#4]
➜  yar-client-java git:(master) php -ddate.timezone=PRC -dextension=yar.so -S 127.0.0.1:8095 -t src/test/resources
[Fri Apr  1 14:31:35 2016] PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.0-rc.3_2/lib/php/extensions/no-debug-non-zts-20141001/yar.so' - dlopen(/usr/local/Cellar/php70/7.0.0-rc.3_2/lib/php/extensions/no-debug-non-zts-20141001/yar.so, 9): image not found in Unknown on line 0
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library '/usr/local/Cellar/php70/7.0.0-rc.3_2/lib/php/extensions/no-debug-non-zts-20141001/yar.so' - dlopen(/usr/local/Cellar/php70/7.0.0-rc.3_2/lib/php/extensions/no-debug-non-zts-20141001/yar.so, 9): image not found in <b>Unknown</b> on line <b>0</b><br />
PHP 7.0.0RC3 Development Server started at Fri Apr  1 14:31:35 2016
Listening on http://127.0.0.1:8095
Document root is /Users/qk/mygithub/yar-client-java/src/test/resources
Press Ctrl-C to quit.
[Fri Apr  1 14:31:39 2016] PHP Fatal error:  Uncaught Error: Class 'Yar_Server' not found in /Users/qk/mygithub/yar-client-java/src/test/resources/yar.php:49
Stack trace:
#0 {main}

  thrown in /Users/qk/mygithub/yar-client-java/src/test/resources/yar.php on line 49
[Fri Apr  1 14:31:39 2016] 127.0.0.1:15637 [200]: /yar.php - Uncaught Error: Class 'Yar_Server' not found in /Users/qk/mygithub/yar-client-java/src/test/resources/yar.php:49
Stack trace:
#0 {main}

  thrown in /Users/qk/mygithub/yar-client-java/src/test/resources/yar.php on line 49

**Comment by rustjson** [comment]
yar 编译的有问题

**Comment by ghost** [comment]
多谢。是我OSX 10.10安装的时候有点问题。正确的安装方法应该是:
http://stackoverflow.com/questions/34850904/error-failed-to-write-failed-to-open-stream-pecl-install-oauth-on-mac-osx-el
